[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polysolve"
authors = [{name = "My name", email = "my_email@email.com"}]
requires-python = ">= 3.8"
readme = "README.md"
description = "Summary of the project here"
license = {text = "Apache"}

keywords = ["keyword1","keyword2"]
dependencies = ["numpy"]
#classifiers = [...]
dynamic = ["version"]

[project.urls]
Homepage="https://github.com/effepivi/polysolve"
Repository="https://github.com/effepivi/polysolve.git"

[tool.setuptools.dynamic]
version = {attr = "polysolve.__version__"}
